cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()

file(READ "${SOURCE_DIR}/CMakeLists.txt" _cmake_lists)
file(READ "${SOURCE_DIR}/CMakePresets.json" _presets)
file(READ "${SOURCE_DIR}/cmake/CompilerSettings.cmake" _compiler_settings)

if(_cmake_lists MATCHES "file[ \t\r\n]*\\([ \t\r\n]*GLOB_RECURSE")
  message(FATAL_ERROR "Application source ownership regressed to recursive globbing")
endif()
if(NOT _cmake_lists MATCHES "add_executable\\(Application")
  message(FATAL_ERROR "The owned Application target is missing")
endif()
if(_cmake_lists MATCHES "MySQLDatabase")
  message(FATAL_ERROR "The unsupported MySQL facade re-entered the application graph")
endif()
if(NOT _cmake_lists MATCHES "WATCHLIST_GENERATED_DIR[^\n]*CMAKE_CURRENT_BINARY_DIR")
  message(FATAL_ERROR "Version artifacts are not rooted in the build tree")
endif()
if(_cmake_lists MATCHES "CMakeUserPresets")
  message(FATAL_ERROR "Tracked configuration must not require a local user preset")
endif()
if(NOT _compiler_settings MATCHES "WATCHLIST_WARNINGS_AS_ERRORS")
  message(FATAL_ERROR "The owned-code warning policy is missing")
endif()
if(NOT _compiler_settings MATCHES "-fsanitize=address,undefined")
  message(FATAL_ERROR "The Clang/GCC ASan+UBSan policy is missing")
endif()
if(NOT _compiler_settings MATCHES "unsupported by MSVC")
  message(FATAL_ERROR "The sanitizer policy lacks an explicit MSVC diagnostic")
endif()

string(JSON _preset_count LENGTH "${_presets}" configurePresets)
set(_required_presets default with-profiling sanitizers)
set(_found_presets)
math(EXPR _last_preset "${_preset_count} - 1")
foreach(_index RANGE 0 ${_last_preset})
  string(JSON _name GET "${_presets}" configurePresets ${_index} name)
  list(APPEND _found_presets "${_name}")
endforeach()
foreach(_required IN LISTS _required_presets)
  if(NOT _required IN_LIST _found_presets)
    message(FATAL_ERROR "Required tracked configure preset '${_required}' is missing")
  endif()
endforeach()

message(STATUS "Application build, preset, version-output, warning, and sanitizer contracts verified")
