cmake_minimum_required(VERSION 3.21)

foreach(_required TEST_CASE MODULE_PATH FIXTURE_DIR TEST_OUTPUT_DIR)
  if(NOT DEFINED ${_required})
    message(FATAL_ERROR "Version pipeline test requires -D${_required}=...")
  endif()
endforeach()

include("${MODULE_PATH}")

function(assert_equal actual expected label)
  if(NOT "${actual}" STREQUAL "${expected}")
    message(FATAL_ERROR "${label}: expected '${expected}', got '${actual}'")
  endif()
endfunction()

function(load_fixture name output)
  file(READ "${FIXTURE_DIR}/${name}.json" _json)
  set(${output} "${_json}" PARENT_SCOPE)
endfunction()

function(expect_failure expected_regex)
  execute_process(
    COMMAND "${CMAKE_COMMAND}"
      "-DTEST_CASE=${TEST_CASE}"
      "-DTEST_CHILD=ON"
      "-DMODULE_PATH=${MODULE_PATH}"
      "-DFIXTURE_DIR=${FIXTURE_DIR}"
      "-DTEST_OUTPUT_DIR=${TEST_OUTPUT_DIR}"
      -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _stdout
    ERROR_VARIABLE _stderr)
  string(CONCAT _output "${_stdout}" "${_stderr}")
  if(_result EQUAL 0)
    message(FATAL_ERROR "${TEST_CASE}: invalid input unexpectedly succeeded")
  endif()
  if(NOT _output MATCHES "${expected_regex}")
    message(FATAL_ERROR
      "${TEST_CASE}: failure did not contain '${expected_regex}'. Output:\n${_output}")
  endif()
endfunction()

function(export_fixture_metadata prefix source)
  set(PROJECT_VERSION "${${prefix}_VERSION}" PARENT_SCOPE)
  foreach(_field MAJOR MINOR PATCH PRERELEASE BUILD BRANCH COMMIT FULL UNCOMMITTED)
    set(PROJECT_VERSION_${_field} "${${prefix}_${_field}}" PARENT_SCOPE)
  endforeach()
  set(WATCHLIST_VERSION_SOURCE "${source}" PARENT_SCOPE)
endfunction()

if(TEST_CASE STREQUAL "valid")
  load_fixture(valid _json)
  watchlist_parse_gitversion_json("${_json}" PARSED)
  assert_equal("${PARSED_FULL}" "1.2.3-beta.4+17" "valid FullSemVer")
  assert_equal("${PARSED_BUILD}" "17" "valid BuildMetaData")
  assert_equal("${PARSED_COMMIT}" "0123456789abcdef0123456789abcdef01234567" "valid Sha")

elseif(TEST_CASE STREQUAL "missing")
  if(TEST_CHILD)
    load_fixture(missing _json)
    watchlist_parse_gitversion_json("${_json}" PARSED)
  else()
    expect_failure("required field 'Patch'")
  endif()

elseif(TEST_CASE STREQUAL "wrong-type")
  if(TEST_CHILD)
    load_fixture(wrong-type _json)
    watchlist_parse_gitversion_json("${_json}" PARSED)
  else()
    expect_failure("field 'Major' must have")
  endif()

elseif(TEST_CASE STREQUAL "escaped")
  load_fixture(escaped _json)
  watchlist_parse_gitversion_json("${_json}" PARSED)
  _watchlist_escape_literal("${PARSED_BRANCH}" _escaped)
  set(_expected [=[feature/quote\"and\\slash]=])
  assert_equal("${_escaped}" "${_expected}" "escaped BranchName")
  export_fixture_metadata(PARSED "GitVersion")
  file(MAKE_DIRECTORY "${TEST_OUTPUT_DIR}")
  generate_version_header("${TEST_OUTPUT_DIR}/Version.hpp")
  file(READ "${TEST_OUTPUT_DIR}/Version.hpp" _header)
  string(FIND "${_header}" "${_expected}" _position)
  if(_position EQUAL -1)
    message(FATAL_ERROR "escaped branch was not preserved in generated C++")
  endif()

elseif(TEST_CASE STREQUAL "non-ascii")
  load_fixture(non-ascii _json)
  watchlist_parse_gitversion_json("${_json}" PARSED)
  assert_equal("${PARSED_BRANCH}" "vývoj/žluťoučký" "non-ASCII BranchName")
  export_fixture_metadata(PARSED "GitVersion")
  file(MAKE_DIRECTORY "${TEST_OUTPUT_DIR}")
  generate_version_header("${TEST_OUTPUT_DIR}/Version.hpp")
  set(_WATCHLIST_GENERATE_RESOURCE_FOR_TESTS ON)
  generate_version_resource("${TEST_OUTPUT_DIR}/version.rc")
  file(READ "${TEST_OUTPUT_DIR}/Version.hpp" _header)
  string(FIND "${_header}" "vývoj/žluťoučký" _position)
  if(_position EQUAL -1)
    message(FATAL_ERROR "non-ASCII branch was not preserved in generated C++")
  endif()

elseif(TEST_CASE STREQUAL "override")
  set(WATCHLIST_VERSION_OVERRIDE "9.8.7-rc.2+archive")
  set(WATCHLIST_REQUIRE_GITVERSION OFF)
  set(WATCHLIST_REQUIRE_CLEAN_PROVENANCE OFF)
  configure_version()
  assert_equal("${WATCHLIST_VERSION_SOURCE}" "override" "override source")
  assert_equal("${PROJECT_VERSION_FULL}" "9.8.7-rc.2+archive" "override full version")
  assert_equal("${PROJECT_VERSION_MAJOR}" "9" "override major")

elseif(TEST_CASE STREQUAL "fallback")
  set(WATCHLIST_VERSION_OVERRIDE "")
  set(_WATCHLIST_DISABLE_GITVERSION_FOR_TESTS ON)
  set(WATCHLIST_REQUIRE_GITVERSION OFF)
  set(WATCHLIST_REQUIRE_CLEAN_PROVENANCE OFF)
  configure_version()
  assert_equal("${WATCHLIST_VERSION_SOURCE}" "development fallback" "fallback source")
  assert_equal("${PROJECT_VERSION_FULL}" "0.0.0-dev+unversioned" "fallback full version")

elseif(TEST_CASE STREQUAL "strict-gitversion")
  if(TEST_CHILD)
    set(WATCHLIST_VERSION_OVERRIDE "")
    set(_WATCHLIST_DISABLE_GITVERSION_FOR_TESTS ON)
    set(WATCHLIST_REQUIRE_GITVERSION ON)
    configure_version()
  else()
    expect_failure("strict GitVersion/provenance policy")
  endif()

elseif(TEST_CASE STREQUAL "strict-provenance")
  if(TEST_CHILD)
    load_fixture(dirty _json)
    set(WATCHLIST_VERSION_OVERRIDE "")
    set(_WATCHLIST_GITVERSION_JSON_FOR_TESTS "${_json}")
    set(WATCHLIST_REQUIRE_CLEAN_PROVENANCE ON)
    configure_version()
  else()
    expect_failure("clean provenance is required")
  endif()

else()
  message(FATAL_ERROR "Unknown version pipeline TEST_CASE '${TEST_CASE}'")
endif()
