#pragma once

// Version.hpp is generated by CMake/GitVersion and should not be manually edited.

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1
#define VERSION_STRING "0.0.1"
#define VERSION_PRERELEASE ""
#define VERSION_BUILD ""
#define VERSION_BRANCH ""
#define VERSION_COMMIT "d52ab3a"
#define VERSION_FULL "0.0.1"